config/routes.rb
Activerse::Engine.routes.draw do
  resources :settings
end

app/models/activerse/application_record.rb
module Activerse
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/activerse/setting.rb
module Activerse
  class Setting < ApplicationRecord
    validates :key, presence: true, uniqueness: true
    validates :value, presence: true
  end
end

app/controllers/activerse/application_controller.rb
module Activerse
  class ApplicationController < ActionController::Base
  end
end

app/controllers/activerse/settings_controller.rb
require_dependency "activerse/application_controller"

module Activerse
  class SettingsController < ApplicationController
    before_action :set_setting, only: [:show, :edit, :update, :destroy]

    def index
      @settings = Setting.all
    end

    def show
    end

    def new
      @setting = Setting.new
    end

    def edit
    end

    def create
      @setting = Setting.new(setting_params)

      if @setting.save
        redirect_to @setting, notice: 'Setting was successfully created.'
      else
        render :new
      end
    end

    def update
      if @setting.update(setting_params)
        redirect_to @setting, notice: 'Setting was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @setting.destroy
      redirect_to settings_url, notice: 'Setting was successfully destroyed.'
    end

  private
    def set_setting
      @setting = Setting.find(params[:id])
    end

    def setting_params
      params.require(:setting).permit(:key, :value)
    end
  end
end

app/helpers/activerse/application_helper.rb
module Activerse
  module ApplicationHelper
  end
end

app/helpers/activerse/settings_helper.rb
module Activerse
  module SettingsHelper
  end
end

app/views/activerse/settings/_form.html.erb
<%= form_with(model: setting) do |form| %>
  <% if setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
        <% setting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :key %>
    <%= form.text_field :key %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/activerse/settings/edit.html.erb
<h1>Editing Setting</h1>

<%= render 'form', setting: @setting %>

<%= link_to 'Show', @setting %> |
<%= link_to 'Back', settings_path %>

app/views/activerse/settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Settings</h1>

<table>
  <thead>
    <tr>
      <th>Key</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= setting.key %></td>
        <td><%= setting.value %></td>
        <td><%= link_to 'Show', setting %></td>
        <td><%= link_to 'Edit', edit_setting_path(setting) %></td>
        <td><%= link_to 'Destroy', setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setting', new_setting_path %>

app/views/activerse/settings/new.html.erb
<h1>New Setting</h1>

<%= render 'form', setting: @setting %>

<%= link_to 'Back', settings_path %>

app/views/activerse/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Key:</strong>
  <%= @setting.key %>
</p>

<p>
  <strong>Value:</strong>
  <%= @setting.value %>
</p>

<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>

app/views/layouts/activerse/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Activerse</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    "activerse/application", media: "all" %>
</head>
<body>

<%= yield %>

</body>
</html>